<a href="https://colab.research.google.com/github/jarratia/yt-analisis-datos/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
#Crear arreglo de una dimensión con 5 elementos
arr1 = np.array([1,2,3,4,5,6])
print(arr1)
print(arr1.shape)
print(arr1.dtype)

[1 2 3 4 5 6]
(6,)
int64


In [5]:
#Crear matrices, tomando el arr1
#Cambiar la forma a una matriz de 2x3 (2 Filas - 3 Columnas)
arr2 = arr1.reshape((2,3))
print(arr2)
print(arr2.shape)
print(arr2.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [ ]:
#Crear un arreglo de 2D con forma de 4x4 con números aleatorios entre 0 - 1
matrix = np.random.rand(4,4)
print(matrix)
print(matrix.shape)
print(matrix.dtype)