<a href="https://colab.research.google.com/github/jarratia/yt-analisis-datos/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

In [7]:
#Crear arreglo de una dimensión con 5 elementos
arr1 = np.array([1,2,3,4,5,6])
print(arr1)
print(arr1.shape)
print(arr1.dtype)

[1 2 3 4 5 6]
(6,)
int32


In [8]:
#Crear matrices, tomando el arr1
#Cambiar la forma a una matriz de 2x3 (2 Filas - 3 Columnas)
arr2 = arr1.reshape((2,3))
print(arr2)
print(arr2.shape)
print(arr2.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int32


In [9]:
#Crear un arreglo de 2D con forma de 4x4 con números aleatorios entre 0 - 1
matrix = np.random.rand(4,4)
print(matrix)
print(matrix.shape)
print(matrix.dtype)

[[0.76884803 0.70832508 0.81247887 0.33988208]
 [0.78633167 0.91560733 0.30656426 0.11889337]
 [0.1413851  0.42410684 0.34315063 0.02470678]
 [0.84848389 0.18933588 0.5897928  0.77549912]]
(4, 4)
float64


In [10]:
#Crear un arreglo de dos dimensiones, a partir de una lista de listas
array = np.array([[1,2,3], [4,5,6], [7,8,9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
#Crear un arreglo de ceros con una forma 3,4
array_zeros = np.zeros((3,4))
array_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])