<a href="https://colab.research.google.com/github/jarratia/yt-analisis-datos/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np

In [18]:
#Crear arreglo de una dimensión con 5 elementos
arr1 = np.array([1,2,3,4,5,6])
print(arr1)
print(arr1.shape)
print(arr1.dtype)

[1 2 3 4 5 6]
(6,)
int32


In [19]:
#Crear matrices, tomando el arr1
#Cambiar la forma a una matriz de 2x3 (2 Filas - 3 Columnas)
arr2 = arr1.reshape((2,3))
print(arr2)
print(arr2.shape)
print(arr2.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int32


In [20]:
#Crear un arreglo de 2D con forma de 4x4 con números aleatorios entre 0 - 1
matrix = np.random.rand(4,4)
print(matrix)
print(matrix.shape)
print(matrix.dtype)

[[0.26075164 0.83010671 0.78231386 0.68898069]
 [0.07304405 0.13364994 0.09323593 0.65866842]
 [0.53772184 0.57307756 0.66341564 0.57739814]
 [0.83681359 0.60866096 0.30365283 0.18869455]]
(4, 4)
float64


In [21]:
#Crear un arreglo de dos dimensiones, a partir de una lista de listas
array = np.array([[1,2,3], [4,5,6], [7,8,9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
#Crear un arreglo de ceros con una forma 3,4
array_zeros = np.zeros((3,4))
array_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
#Crear una matriz identidad
matriz_identidad = np.eye(4)
matriz_identidad

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
#Crear un arreglo 3D de 0 con una forma (2,3,4)
array3D = np.zeros((4,4,4))
array3D

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [28]:
arr = np.random.rand(2,5)
arr

array([[0.93685829, 0.07577028, 0.05061782, 0.09493275, 0.34310847],
       [0.5663197 , 0.1097018 , 0.18797172, 0.49957295, 0.89175646]])

In [29]:
arr.T

array([[0.93685829, 0.5663197 ],
       [0.07577028, 0.1097018 ],
       [0.05061782, 0.18797172],
       [0.09493275, 0.49957295],
       [0.34310847, 0.89175646]])

In [30]:
arra1 = np.array([[1,2], [3,4]])
arra2 = np.array([[5,6], [7,8]])

arr1, arr2

(array([1, 2, 3, 4, 5, 6]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [31]:
#Concatenear arreglos horizontalmente
arr_h = np.hstack((arra1, arra2))
arr_h

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [32]:
#Concatenar de forma vertital
arr_v = np.vstack((arra1, arra2))
arr_v

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])